# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tof_preprocessing/AgentMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AgentMsg(genpy.Message):
  _md5sum = "b8130ef0752937d05f659f991421dc66"
  _type = "tof_preprocessing/AgentMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 id
float32 cx
float32 cy
float32 vx
float32 vy
int32 x
int32 y
int32 w
int32 h
int32 age
string state
"""
  __slots__ = ['id','cx','cy','vx','vy','x','y','w','h','age','state']
  _slot_types = ['int32','float32','float32','float32','float32','int32','int32','int32','int32','int32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,cx,cy,vx,vy,x,y,w,h,age,state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AgentMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.cx is None:
        self.cx = 0.
      if self.cy is None:
        self.cy = 0.
      if self.vx is None:
        self.vx = 0.
      if self.vy is None:
        self.vy = 0.
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
      if self.w is None:
        self.w = 0
      if self.h is None:
        self.h = 0
      if self.age is None:
        self.age = 0
      if self.state is None:
        self.state = ''
    else:
      self.id = 0
      self.cx = 0.
      self.cy = 0.
      self.vx = 0.
      self.vy = 0.
      self.x = 0
      self.y = 0
      self.w = 0
      self.h = 0
      self.age = 0
      self.state = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i4f5i().pack(_x.id, _x.cx, _x.cy, _x.vx, _x.vy, _x.x, _x.y, _x.w, _x.h, _x.age))
      _x = self.state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.id, _x.cx, _x.cy, _x.vx, _x.vy, _x.x, _x.y, _x.w, _x.h, _x.age,) = _get_struct_i4f5i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i4f5i().pack(_x.id, _x.cx, _x.cy, _x.vx, _x.vy, _x.x, _x.y, _x.w, _x.h, _x.age))
      _x = self.state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.id, _x.cx, _x.cy, _x.vx, _x.vy, _x.x, _x.y, _x.w, _x.h, _x.age,) = _get_struct_i4f5i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.state = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.state = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i4f5i = None
def _get_struct_i4f5i():
    global _struct_i4f5i
    if _struct_i4f5i is None:
        _struct_i4f5i = struct.Struct("<i4f5i")
    return _struct_i4f5i
