# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tof_preprocessing/Blob.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Blob(genpy.Message):
  _md5sum = "ae73ff5c5745f08a16d613edb0951120"
  _type = "tof_preprocessing/Blob"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 id
float32 cx
float32 cy
int32 x
int32 y
int32 w
int32 h
float32 area
bool is_static
"""
  __slots__ = ['id','cx','cy','x','y','w','h','area','is_static']
  _slot_types = ['int32','float32','float32','int32','int32','int32','int32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,cx,cy,x,y,w,h,area,is_static

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Blob, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.cx is None:
        self.cx = 0.
      if self.cy is None:
        self.cy = 0.
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
      if self.w is None:
        self.w = 0
      if self.h is None:
        self.h = 0
      if self.area is None:
        self.area = 0.
      if self.is_static is None:
        self.is_static = False
    else:
      self.id = 0
      self.cx = 0.
      self.cy = 0.
      self.x = 0
      self.y = 0
      self.w = 0
      self.h = 0
      self.area = 0.
      self.is_static = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2f4ifB().pack(_x.id, _x.cx, _x.cy, _x.x, _x.y, _x.w, _x.h, _x.area, _x.is_static))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.id, _x.cx, _x.cy, _x.x, _x.y, _x.w, _x.h, _x.area, _x.is_static,) = _get_struct_i2f4ifB().unpack(str[start:end])
      self.is_static = bool(self.is_static)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2f4ifB().pack(_x.id, _x.cx, _x.cy, _x.x, _x.y, _x.w, _x.h, _x.area, _x.is_static))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.id, _x.cx, _x.cy, _x.x, _x.y, _x.w, _x.h, _x.area, _x.is_static,) = _get_struct_i2f4ifB().unpack(str[start:end])
      self.is_static = bool(self.is_static)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2f4ifB = None
def _get_struct_i2f4ifB():
    global _struct_i2f4ifB
    if _struct_i2f4ifB is None:
        _struct_i2f4ifB = struct.Struct("<i2f4ifB")
    return _struct_i2f4ifB
