// Generated by gencpp from file tof_preprocessing/AgentArray.msg
// DO NOT EDIT!


#ifndef TOF_PREPROCESSING_MESSAGE_AGENTARRAY_H
#define TOF_PREPROCESSING_MESSAGE_AGENTARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tof_preprocessing/AgentMsg.h>

namespace tof_preprocessing
{
template <class ContainerAllocator>
struct AgentArray_
{
  typedef AgentArray_<ContainerAllocator> Type;

  AgentArray_()
    : header()
    , agents()  {
    }
  AgentArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , agents(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tof_preprocessing::AgentMsg_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tof_preprocessing::AgentMsg_<ContainerAllocator> >> _agents_type;
  _agents_type agents;





  typedef boost::shared_ptr< ::tof_preprocessing::AgentArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tof_preprocessing::AgentArray_<ContainerAllocator> const> ConstPtr;

}; // struct AgentArray_

typedef ::tof_preprocessing::AgentArray_<std::allocator<void> > AgentArray;

typedef boost::shared_ptr< ::tof_preprocessing::AgentArray > AgentArrayPtr;
typedef boost::shared_ptr< ::tof_preprocessing::AgentArray const> AgentArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tof_preprocessing::AgentArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tof_preprocessing::AgentArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tof_preprocessing::AgentArray_<ContainerAllocator1> & lhs, const ::tof_preprocessing::AgentArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.agents == rhs.agents;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tof_preprocessing::AgentArray_<ContainerAllocator1> & lhs, const ::tof_preprocessing::AgentArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tof_preprocessing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tof_preprocessing::AgentArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tof_preprocessing::AgentArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tof_preprocessing::AgentArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tof_preprocessing::AgentArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tof_preprocessing::AgentArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tof_preprocessing::AgentArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tof_preprocessing::AgentArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "78053eb215ec82a8b9dde5f1fe7feddf";
  }

  static const char* value(const ::tof_preprocessing::AgentArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x78053eb215ec82a8ULL;
  static const uint64_t static_value2 = 0xb9dde5f1fe7feddfULL;
};

template<class ContainerAllocator>
struct DataType< ::tof_preprocessing::AgentArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tof_preprocessing/AgentArray";
  }

  static const char* value(const ::tof_preprocessing::AgentArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tof_preprocessing::AgentArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"AgentMsg[] agents\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tof_preprocessing/AgentMsg\n"
"int32 id\n"
"float32 cx\n"
"float32 cy\n"
"float32 vx\n"
"float32 vy\n"
"int32 x\n"
"int32 y\n"
"int32 w\n"
"int32 h\n"
"int32 age\n"
"string state\n"
;
  }

  static const char* value(const ::tof_preprocessing::AgentArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tof_preprocessing::AgentArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.agents);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgentArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tof_preprocessing::AgentArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tof_preprocessing::AgentArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "agents: ";
    if (v.agents.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.agents.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::tof_preprocessing::AgentMsg_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.agents[i]);
    }
    if (v.agents.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOF_PREPROCESSING_MESSAGE_AGENTARRAY_H
