// Generated by gencpp from file tof_preprocessing/AgentMsg.msg
// DO NOT EDIT!


#ifndef TOF_PREPROCESSING_MESSAGE_AGENTMSG_H
#define TOF_PREPROCESSING_MESSAGE_AGENTMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tof_preprocessing
{
template <class ContainerAllocator>
struct AgentMsg_
{
  typedef AgentMsg_<ContainerAllocator> Type;

  AgentMsg_()
    : id(0)
    , cx(0.0)
    , cy(0.0)
    , vx(0.0)
    , vy(0.0)
    , x(0)
    , y(0)
    , w(0)
    , h(0)
    , age(0)
    , state()  {
    }
  AgentMsg_(const ContainerAllocator& _alloc)
    : id(0)
    , cx(0.0)
    , cy(0.0)
    , vx(0.0)
    , vy(0.0)
    , x(0)
    , y(0)
    , w(0)
    , h(0)
    , age(0)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef float _cx_type;
  _cx_type cx;

   typedef float _cy_type;
  _cy_type cy;

   typedef float _vx_type;
  _vx_type vx;

   typedef float _vy_type;
  _vy_type vy;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _w_type;
  _w_type w;

   typedef int32_t _h_type;
  _h_type h;

   typedef int32_t _age_type;
  _age_type age;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::tof_preprocessing::AgentMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tof_preprocessing::AgentMsg_<ContainerAllocator> const> ConstPtr;

}; // struct AgentMsg_

typedef ::tof_preprocessing::AgentMsg_<std::allocator<void> > AgentMsg;

typedef boost::shared_ptr< ::tof_preprocessing::AgentMsg > AgentMsgPtr;
typedef boost::shared_ptr< ::tof_preprocessing::AgentMsg const> AgentMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tof_preprocessing::AgentMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tof_preprocessing::AgentMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tof_preprocessing::AgentMsg_<ContainerAllocator1> & lhs, const ::tof_preprocessing::AgentMsg_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.cx == rhs.cx &&
    lhs.cy == rhs.cy &&
    lhs.vx == rhs.vx &&
    lhs.vy == rhs.vy &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.w == rhs.w &&
    lhs.h == rhs.h &&
    lhs.age == rhs.age &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tof_preprocessing::AgentMsg_<ContainerAllocator1> & lhs, const ::tof_preprocessing::AgentMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tof_preprocessing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tof_preprocessing::AgentMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tof_preprocessing::AgentMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tof_preprocessing::AgentMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tof_preprocessing::AgentMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tof_preprocessing::AgentMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tof_preprocessing::AgentMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tof_preprocessing::AgentMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8130ef0752937d05f659f991421dc66";
  }

  static const char* value(const ::tof_preprocessing::AgentMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8130ef0752937d0ULL;
  static const uint64_t static_value2 = 0x5f659f991421dc66ULL;
};

template<class ContainerAllocator>
struct DataType< ::tof_preprocessing::AgentMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tof_preprocessing/AgentMsg";
  }

  static const char* value(const ::tof_preprocessing::AgentMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tof_preprocessing::AgentMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"float32 cx\n"
"float32 cy\n"
"float32 vx\n"
"float32 vy\n"
"int32 x\n"
"int32 y\n"
"int32 w\n"
"int32 h\n"
"int32 age\n"
"string state\n"
;
  }

  static const char* value(const ::tof_preprocessing::AgentMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tof_preprocessing::AgentMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.cx);
      stream.next(m.cy);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
      stream.next(m.age);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgentMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tof_preprocessing::AgentMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tof_preprocessing::AgentMsg_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cx: ";
    Printer<float>::stream(s, indent + "  ", v.cx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cy: ";
    Printer<float>::stream(s, indent + "  ", v.cy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vx: ";
    Printer<float>::stream(s, indent + "  ", v.vx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vy: ";
    Printer<float>::stream(s, indent + "  ", v.vy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "w: ";
    Printer<int32_t>::stream(s, indent + "  ", v.w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "h: ";
    Printer<int32_t>::stream(s, indent + "  ", v.h);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOF_PREPROCESSING_MESSAGE_AGENTMSG_H
