// Generated by gencpp from file tof_preprocessing/Blob.msg
// DO NOT EDIT!


#ifndef TOF_PREPROCESSING_MESSAGE_BLOB_H
#define TOF_PREPROCESSING_MESSAGE_BLOB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tof_preprocessing
{
template <class ContainerAllocator>
struct Blob_
{
  typedef Blob_<ContainerAllocator> Type;

  Blob_()
    : id(0)
    , cx(0.0)
    , cy(0.0)
    , x(0)
    , y(0)
    , w(0)
    , h(0)
    , area(0.0)
    , is_static(false)  {
    }
  Blob_(const ContainerAllocator& _alloc)
    : id(0)
    , cx(0.0)
    , cy(0.0)
    , x(0)
    , y(0)
    , w(0)
    , h(0)
    , area(0.0)
    , is_static(false)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef float _cx_type;
  _cx_type cx;

   typedef float _cy_type;
  _cy_type cy;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _w_type;
  _w_type w;

   typedef int32_t _h_type;
  _h_type h;

   typedef float _area_type;
  _area_type area;

   typedef uint8_t _is_static_type;
  _is_static_type is_static;





  typedef boost::shared_ptr< ::tof_preprocessing::Blob_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tof_preprocessing::Blob_<ContainerAllocator> const> ConstPtr;

}; // struct Blob_

typedef ::tof_preprocessing::Blob_<std::allocator<void> > Blob;

typedef boost::shared_ptr< ::tof_preprocessing::Blob > BlobPtr;
typedef boost::shared_ptr< ::tof_preprocessing::Blob const> BlobConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tof_preprocessing::Blob_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tof_preprocessing::Blob_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tof_preprocessing::Blob_<ContainerAllocator1> & lhs, const ::tof_preprocessing::Blob_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.cx == rhs.cx &&
    lhs.cy == rhs.cy &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.w == rhs.w &&
    lhs.h == rhs.h &&
    lhs.area == rhs.area &&
    lhs.is_static == rhs.is_static;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tof_preprocessing::Blob_<ContainerAllocator1> & lhs, const ::tof_preprocessing::Blob_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tof_preprocessing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tof_preprocessing::Blob_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tof_preprocessing::Blob_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tof_preprocessing::Blob_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tof_preprocessing::Blob_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tof_preprocessing::Blob_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tof_preprocessing::Blob_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tof_preprocessing::Blob_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae73ff5c5745f08a16d613edb0951120";
  }

  static const char* value(const ::tof_preprocessing::Blob_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae73ff5c5745f08aULL;
  static const uint64_t static_value2 = 0x16d613edb0951120ULL;
};

template<class ContainerAllocator>
struct DataType< ::tof_preprocessing::Blob_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tof_preprocessing/Blob";
  }

  static const char* value(const ::tof_preprocessing::Blob_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tof_preprocessing::Blob_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"float32 cx\n"
"float32 cy\n"
"int32 x\n"
"int32 y\n"
"int32 w\n"
"int32 h\n"
"float32 area\n"
"bool is_static\n"
;
  }

  static const char* value(const ::tof_preprocessing::Blob_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tof_preprocessing::Blob_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.cx);
      stream.next(m.cy);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
      stream.next(m.area);
      stream.next(m.is_static);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Blob_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tof_preprocessing::Blob_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tof_preprocessing::Blob_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cx: ";
    Printer<float>::stream(s, indent + "  ", v.cx);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "cy: ";
    Printer<float>::stream(s, indent + "  ", v.cy);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "w: ";
    Printer<int32_t>::stream(s, indent + "  ", v.w);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "h: ";
    Printer<int32_t>::stream(s, indent + "  ", v.h);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "area: ";
    Printer<float>::stream(s, indent + "  ", v.area);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_static: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_static);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOF_PREPROCESSING_MESSAGE_BLOB_H
