// Generated by gencpp from file tof_preprocessing/BlobArray.msg
// DO NOT EDIT!


#ifndef TOF_PREPROCESSING_MESSAGE_BLOBARRAY_H
#define TOF_PREPROCESSING_MESSAGE_BLOBARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tof_preprocessing/Blob.h>

namespace tof_preprocessing
{
template <class ContainerAllocator>
struct BlobArray_
{
  typedef BlobArray_<ContainerAllocator> Type;

  BlobArray_()
    : header()
    , blobs()  {
    }
  BlobArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , blobs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tof_preprocessing::Blob_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tof_preprocessing::Blob_<ContainerAllocator> >> _blobs_type;
  _blobs_type blobs;





  typedef boost::shared_ptr< ::tof_preprocessing::BlobArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tof_preprocessing::BlobArray_<ContainerAllocator> const> ConstPtr;

}; // struct BlobArray_

typedef ::tof_preprocessing::BlobArray_<std::allocator<void> > BlobArray;

typedef boost::shared_ptr< ::tof_preprocessing::BlobArray > BlobArrayPtr;
typedef boost::shared_ptr< ::tof_preprocessing::BlobArray const> BlobArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tof_preprocessing::BlobArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tof_preprocessing::BlobArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tof_preprocessing::BlobArray_<ContainerAllocator1> & lhs, const ::tof_preprocessing::BlobArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.blobs == rhs.blobs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tof_preprocessing::BlobArray_<ContainerAllocator1> & lhs, const ::tof_preprocessing::BlobArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tof_preprocessing

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tof_preprocessing::BlobArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tof_preprocessing::BlobArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tof_preprocessing::BlobArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tof_preprocessing::BlobArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tof_preprocessing::BlobArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tof_preprocessing::BlobArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tof_preprocessing::BlobArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d70469d6a9ebe44f0592672765104aff";
  }

  static const char* value(const ::tof_preprocessing::BlobArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd70469d6a9ebe44fULL;
  static const uint64_t static_value2 = 0x0592672765104affULL;
};

template<class ContainerAllocator>
struct DataType< ::tof_preprocessing::BlobArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tof_preprocessing/BlobArray";
  }

  static const char* value(const ::tof_preprocessing::BlobArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tof_preprocessing::BlobArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Blob[] blobs\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tof_preprocessing/Blob\n"
"int32 id\n"
"float32 cx\n"
"float32 cy\n"
"int32 x\n"
"int32 y\n"
"int32 w\n"
"int32 h\n"
"float32 area\n"
"bool is_static\n"
;
  }

  static const char* value(const ::tof_preprocessing::BlobArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tof_preprocessing::BlobArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.blobs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlobArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tof_preprocessing::BlobArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tof_preprocessing::BlobArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "blobs: ";
    if (v.blobs.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.blobs.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::tof_preprocessing::Blob_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.blobs[i]);
    }
    if (v.blobs.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOF_PREPROCESSING_MESSAGE_BLOBARRAY_H
